version: '3.3'

services:
  db:
    image: postgres:9.6.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111111
      POSTGRES_DB: testdb
    volumes:
      - pg_ex:/var/lib/postgresql/data

  pgadmin:
    image: thajeztah/pgadmin4
    ports:
      - 5050:5050
    volumes:
      - pg_admin:/pgadmin
    depends_on:
      - db


  psql:
    image: postgres:9.6.3
    entrypoint: psql
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: 111111
    depends_on:
      - db

volumes:
  pg_ex:
  pg_admin:

